baseurl: "/"
permalink: pretty
title: "Studio bienléché décoration et architecture intérieur"
collections_dir: collections
markdown: kramdown
highlighter: rouge

sass:
  indentWidth: 4
  style: compact
  precision: 10

google_analytics_id: false # replace with "UA-XXXX"

logo:
  logo_desktop_image: assets/images/logo/logo.svg
  logo_mobile_image: assets/images/logo/logo-mobile.svg
  logo_mobile_text: ""
  logo_desktop_height: "36px"
  logo_desktop_width: "36px"
  logo_mobile_height: "36px"
  logo_mobile_width: "36px"

plugins:
  - jekyll-environment-variables
  - jekyll-postcss
  - jekyll-paginate

paginate: 3
paginate_path: /blog/page:num/

collections:
  posts:
    output: true
    permalink: /blog/:path/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: "images"
    values:
      image: true
  - scope:
      path: "categories"
    values:
      layout: category
      permalink: /category/:basename/
